-- AlterTable
ALTER TABLE "DictData" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;

-- AlterTable
ALTER TABLE "DictType" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Menu" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Permission" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Role" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "remark" DROP NOT NULL,
ALTER COLUMN "remark" DROP DEFAULT;
